lock table tabla_prueba111 in exclusive mode nowait;

ALTER TABLE tabla_prueba111 NOLOGGING;

ALTER TABLE tabla_prueba111 MODIFY PARTITION P2007 UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION P2008 UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION P2009 UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION P2010 UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION MAXPART UNUSABLE LOCAL INDEXES;

ALTER SESSION SET SKIP_UNUSABLE_INDEXES = TRUE;

INSERT /*+APPEND NO_PARALLEL(tabla_prueba111)*/ INTO tabla_prueba111 PARTITION(P2010)
SELECT /*+FULL(F) NO_PARALLEL(F) */ *
FROM esquema.tabla_prueba111 PARTITION(P2010) F
WHERE FECHA_PROCESO BETWEEN TO_DATE('2010-01-01','YYYY-MM-DD') AND TO_DATE('2010-06-30','YYYY-MM-DD')

COMMIT;


ALTER TABLE tabla_prueba111 MODIFY PARTITION P2007 REBUILD UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION P2008 REBUILD UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION P2009 REBUILD UNUSABLE LOCAL INDEXES;
ALTER TABLE tabla_prueba111 MODIFY PARTITION P2010 REBUILD UNUSABLE LOCAL INDEXES;

ALTER TABLE tabla_prueba111 MODIFY PARTITION MAXPART REBUILD UNUSABLE LOCAL INDEXES;

ALTER SESSION SET SKIP_UNUSABLE_INDEXES = FALSE;

ALTER TABLE tabla_prueba111 LOGGING;
